// <auto-generated />
using System;
using FormBuilder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230807085309_EditAttributeSchemaTable")]
    partial class EditAttributeSchemaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormBuilder.Models.AttributeSchema", b =>
                {
                    b.Property<int>("AttributeSchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeSchemaId"));

                    b.Property<int>("AttributeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitySchemaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxLen")
                        .HasColumnType("int");

                    b.Property<int?>("MinLen")
                        .HasColumnType("int");

                    b.HasKey("AttributeSchemaId");

                    b.HasIndex("AttributeTypeId");

                    b.HasIndex("EntitySchemaId");

                    b.ToTable("AttributeSchemas");
                });

            modelBuilder.Entity("FormBuilder.Models.AttributeType", b =>
                {
                    b.Property<int>("AttributeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeTypeId"));

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttributeTypeId");

                    b.ToTable("AttributeTypes");
                });

            modelBuilder.Entity("FormBuilder.Models.EntityFroms", b =>
                {
                    b.Property<int>("EntityFromsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityFromsId"));

                    b.Property<string>("EntityFromsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitySchemaId")
                        .HasColumnType("int");

                    b.Property<string>("FromJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityFromsId");

                    b.HasIndex("EntitySchemaId");

                    b.ToTable("EntityFroms");
                });

            modelBuilder.Entity("FormBuilder.Models.EntitySchema", b =>
                {
                    b.Property<int>("EntitySchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntitySchemaId"));

                    b.Property<int>("EntityCode")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntitySchemaId");

                    b.ToTable("entitySchemas");
                });

            modelBuilder.Entity("FormBuilder.Models.Tables.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FormBuilder.Models.Tables.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FormBuilder.Models.AttributeSchema", b =>
                {
                    b.HasOne("FormBuilder.Models.AttributeType", "AttributeType")
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Models.EntitySchema", null)
                        .WithMany("AttributeSchemas")
                        .HasForeignKey("EntitySchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeType");
                });

            modelBuilder.Entity("FormBuilder.Models.EntityFroms", b =>
                {
                    b.HasOne("FormBuilder.Models.EntitySchema", "EntitySchema")
                        .WithMany()
                        .HasForeignKey("EntitySchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitySchema");
                });

            modelBuilder.Entity("FormBuilder.Models.Tables.Employee", b =>
                {
                    b.HasOne("FormBuilder.Models.Tables.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormBuilder.Models.EntitySchema", b =>
                {
                    b.Navigation("AttributeSchemas");
                });

            modelBuilder.Entity("FormBuilder.Models.Tables.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
