// <auto-generated />
using System;
using FormBuilder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormBuilder.Models.AttributeSchema", b =>
                {
                    b.Property<int>("AttributeSchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeSchemaId"));

                    b.Property<int>("AttributeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitySchemaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LogicalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxLen")
                        .HasColumnType("int");

                    b.Property<int?>("MinLen")
                        .HasColumnType("int");

                    b.HasKey("AttributeSchemaId");

                    b.HasIndex("AttributeTypeId");

                    b.ToTable("AttributeSchemas");
                });

            modelBuilder.Entity("FormBuilder.Models.AttributeType", b =>
                {
                    b.Property<int>("AttributeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeTypeId"));

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SqlType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttributeTypeId");

                    b.ToTable("AttributeTypes");
                });

            modelBuilder.Entity("FormBuilder.Models.EntityFroms", b =>
                {
                    b.Property<int>("EntityFromsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityFromsId"));

                    b.Property<string>("EntityFromsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitySchemaId")
                        .HasColumnType("int");

                    b.Property<string>("FromJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityFromsId");

                    b.HasIndex("EntitySchemaId");

                    b.ToTable("EntityFroms");
                });

            modelBuilder.Entity("FormBuilder.Models.EntitySchema", b =>
                {
                    b.Property<int>("EntitySchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntitySchemaId"));

                    b.Property<int>("EntityCode")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntitySchemaId");

                    b.ToTable("entitySchemas");
                });

            modelBuilder.Entity("FormBuilder.Models.AttributeSchema", b =>
                {
                    b.HasOne("FormBuilder.Models.AttributeType", "AttributeType")
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeType");
                });

            modelBuilder.Entity("FormBuilder.Models.EntityFroms", b =>
                {
                    b.HasOne("FormBuilder.Models.EntitySchema", "EntitySchema")
                        .WithMany()
                        .HasForeignKey("EntitySchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntitySchema");
                });
#pragma warning restore 612, 618
        }
    }
}
